class TestFailure(Exception):
    """
    Exception raised if a test fails
    """
    def __init__(self):
        pass